# Use official Node image
FROM node:23-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the frontend source code
COPY . .

# Optional: Build app (if this is production)
# ENV NEXT_IGNORE_ESLINT=true
# ENV NEXT_DISABLE_TYPE_CHECKING=true
# RUN npm run build

# Expose port used by React dev server
EXPOSE 3000

# Start React dev server
CMD ["npm", "run", "dev"]